In [1]:
from nba_api.stats.endpoints import leaguegamelog
import json

In [2]:
extract = leaguegamelog.LeagueGameLog(
        player_or_team_abbreviation='P', # 'P' for Player stats
        season='2025-26',
        season_type_all_star='Regular Season'
    )

In [10]:
extract_json = extract.get_json()
extract_normalized_json = extract.get_normalized_json()
extract_df = extract.get_data_frames()[0]

In [12]:
cog = json.loads(extract_json)
cog2 = json.loads(extract_normalized_json)

In [16]:
cog2['LeagueGameLog']

[{'SEASON_ID': '22025',
  'PLAYER_ID': 1642964,
  'PLAYER_NAME': 'Brooks Barnhizer',
  'TEAM_ID': 1610612760,
  'TEAM_ABBREVIATION': 'OKC',
  'TEAM_NAME': 'Oklahoma City Thunder',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'OKC vs. HOU',
  'WL': 'W',
  'MIN': 2,
  'FGM': 0,
  'FGA': 0,
  'FG_PCT': None,
  'FG3M': 0,
  'FG3A': 0,
  'FG3_PCT': None,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 0,
  'DREB': 0,
  'REB': 0,
  'AST': 0,
  'STL': 0,
  'BLK': 0,
  'TOV': 0,
  'PF': 0,
  'PTS': 0,
  'PLUS_MINUS': -2,
  'FANTASY_PTS': 0.0,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1642959,
  'PLAYER_NAME': 'Chris Youngblood',
  'TEAM_ID': 1610612760,
  'TEAM_ABBREVIATION': 'OKC',
  'TEAM_NAME': 'Oklahoma City Thunder',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'OKC vs. HOU',
  'WL': 'W',
  'MIN': 0,
  'FGM': 0,
  'FGA': 0,
  'FG_PCT': None,
  'FG3M': 0,
  'FG3A': 0,
  'FG3_PCT': None,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 0,
  'DREB': 0,
  'REB': 0,
  'AST': 0,
  'STL': 0,
  'BLK': 0,
  'TOV': 0,
  'PF': 0,
  'PTS': 0,
  'PLUS_MINUS': 0,
  'FANTASY_PTS': 0.0,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1641717,
  'PLAYER_NAME': 'Cason Wallace',
  'TEAM_ID': 1610612760,
  'TEAM_ABBREVIATION': 'OKC',
  'TEAM_NAME': 'Oklahoma City Thunder',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'OKC vs. HOU',
  'WL': 'W',
  'MIN': 42,
  'FGM': 5,
  'FGA': 10,
  'FG_PCT': 0.5,
  'FG3M': 3,
  'FG3A': 8,
  'FG3_PCT': 0.375,
  'FTM': 1,
  'FTA': 2,
  'FT_PCT': 0.5,
  'OREB': 1,
  'DREB': 6,
  'REB': 7,
  'AST': 5,
  'STL': 4,
  'BLK': 0,
  'TOV': 2,
  'PF': 3,
  'PTS': 14,
  'PLUS_MINUS': 8,
  'FANTASY_PTS': 39.9,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1631119,
  'PLAYER_NAME': 'Jaylin Williams',
  'TEAM_ID': 1610612760,
  'TEAM_ABBREVIATION': 'OKC',
  'TEAM_NAME': 'Oklahoma City Thunder',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'OKC vs. HOU',
  'WL': 'W',
  'MIN': 13,
  'FGM': 1,
  'FGA': 5,
  'FG_PCT': 0.2,
  'FG3M': 0,
  'FG3A': 4,
  'FG3_PCT': 0.0,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 0,
  'DREB': 0,
  'REB': 0,
  'AST': 1,
  'STL': 1,
  'BLK': 0,
  'TOV': 0,
  'PF': 1,
  'PTS': 2,
  'PLUS_MINUS': -3,
  'FANTASY_PTS': 6.5,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1631096,
  'PLAYER_NAME': 'Chet Holmgren',
  'TEAM_ID': 1610612760,
  'TEAM_ABBREVIATION': 'OKC',
  'TEAM_NAME': 'Oklahoma City Thunder',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'OKC vs. HOU',
  'WL': 'W',
  'MIN': 38,
  'FGM': 11,
  'FGA': 17,
  'FG_PCT': 0.647,
  'FG3M': 2,
  'FG3A': 5,
  'FG3_PCT': 0.4,
  'FTM': 4,
  'FTA': 4,
  'FT_PCT': 1.0,
  'OREB': 2,
  'DREB': 5,
  'REB': 7,
  'AST': 2,
  'STL': 0,
  'BLK': 0,
  'TOV': 3,
  'PF': 6,
  'PTS': 28,
  'PLUS_MINUS': -1,
  'FANTASY_PTS': 36.4,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1630598,
  'PLAYER_NAME': 'Aaron Wiggins',
  'TEAM_ID': 1610612760,
  'TEAM_ABBREVIATION': 'OKC',
  'TEAM_NAME': 'Oklahoma City Thunder',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'OKC vs. HOU',
  'WL': 'W',
  'MIN': 21,
  'FGM': 4,
  'FGA': 8,
  'FG_PCT': 0.5,
  'FG3M': 2,
  'FG3A': 5,
  'FG3_PCT': 0.4,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 0,
  'DREB': 1,
  'REB': 1,
  'AST': 1,
  'STL': 0,
  'BLK': 0,
  'TOV': 1,
  'PF': 1,
  'PTS': 10,
  'PLUS_MINUS': 2,
  'FANTASY_PTS': 11.7,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1629652,
  'PLAYER_NAME': 'Luguentz Dort',
  'TEAM_ID': 1610612760,
  'TEAM_ABBREVIATION': 'OKC',
  'TEAM_NAME': 'Oklahoma City Thunder',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'OKC vs. HOU',
  'WL': 'W',
  'MIN': 45,
  'FGM': 2,
  'FGA': 12,
  'FG_PCT': 0.167,
  'FG3M': 0,
  'FG3A': 8,
  'FG3_PCT': 0.0,
  'FTM': 2,
  'FTA': 2,
  'FT_PCT': 1.0,
  'OREB': 2,
  'DREB': 4,
  'REB': 6,
  'AST': 5,
  'STL': 1,
  'BLK': 0,
  'TOV': 1,
  'PF': 4,
  'PTS': 6,
  'PLUS_MINUS': 2,
  'FANTASY_PTS': 22.7,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1628983,
  'PLAYER_NAME': 'Shai Gilgeous-Alexander',
  'TEAM_ID': 1610612760,
  'TEAM_ABBREVIATION': 'OKC',
  'TEAM_NAME': 'Oklahoma City Thunder',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'OKC vs. HOU',
  'WL': 'W',
  'MIN': 47,
  'FGM': 12,
  'FGA': 26,
  'FG_PCT': 0.462,
  'FG3M': 1,
  'FG3A': 9,
  'FG3_PCT': 0.111,
  'FTM': 10,
  'FTA': 14,
  'FT_PCT': 0.714,
  'OREB': 0,
  'DREB': 5,
  'REB': 5,
  'AST': 5,
  'STL': 2,
  'BLK': 2,
  'TOV': 3,
  'PF': 2,
  'PTS': 35,
  'PLUS_MINUS': 3,
  'FANTASY_PTS': 57.5,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1627936,
  'PLAYER_NAME': 'Alex Caruso',
  'TEAM_ID': 1610612760,
  'TEAM_ABBREVIATION': 'OKC',
  'TEAM_NAME': 'Oklahoma City Thunder',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'OKC vs. HOU',
  'WL': 'W',
  'MIN': 30,
  'FGM': 3,
  'FGA': 9,
  'FG_PCT': 0.333,
  'FG3M': 2,
  'FG3A': 6,
  'FG3_PCT': 0.333,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 0,
  'DREB': 2,
  'REB': 2,
  'AST': 3,
  'STL': 2,
  'BLK': 1,
  'TOV': 0,
  'PF': 2,
  'PTS': 8,
  'PLUS_MINUS': -15,
  'FANTASY_PTS': 23.9,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1642263,
  'PLAYER_NAME': 'Reed Sheppard',
  'TEAM_ID': 1610612745,
  'TEAM_ABBREVIATION': 'HOU',
  'TEAM_NAME': 'Houston Rockets',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'HOU @ OKC',
  'WL': 'L',
  'MIN': 28,
  'FGM': 3,
  'FGA': 11,
  'FG_PCT': 0.273,
  'FG3M': 2,
  'FG3A': 7,
  'FG3_PCT': 0.286,
  'FTM': 1,
  'FTA': 2,
  'FT_PCT': 0.5,
  'OREB': 1,
  'DREB': 1,
  'REB': 2,
  'AST': 4,
  'STL': 1,
  'BLK': 1,
  'TOV': 2,
  'PF': 1,
  'PTS': 9,
  'PLUS_MINUS': 0,
  'FANTASY_PTS': 21.4,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1641708,
  'PLAYER_NAME': 'Amen Thompson',
  'TEAM_ID': 1610612745,
  'TEAM_ABBREVIATION': 'HOU',
  'TEAM_NAME': 'Houston Rockets',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'HOU @ OKC',
  'WL': 'L',
  'MIN': 39,
  'FGM': 8,
  'FGA': 17,
  'FG_PCT': 0.471,
  'FG3M': 0,
  'FG3A': 7,
  'FG3_PCT': 0.0,
  'FTM': 2,
  'FTA': 2,
  'FT_PCT': 1.0,
  'OREB': 2,
  'DREB': 2,
  'REB': 4,
  'AST': 5,
  'STL': 1,
  'BLK': 1,
  'TOV': 4,
  'PF': 3,
  'PTS': 18,
  'PLUS_MINUS': -11,
  'FANTASY_PTS': 32.3,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1631095,
  'PLAYER_NAME': 'Jabari Smith Jr.',
  'TEAM_ID': 1610612745,
  'TEAM_ABBREVIATION': 'HOU',
  'TEAM_NAME': 'Houston Rockets',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'HOU @ OKC',
  'WL': 'L',
  'MIN': 42,
  'FGM': 7,
  'FGA': 15,
  'FG_PCT': 0.467,
  'FG3M': 2,
  'FG3A': 6,
  'FG3_PCT': 0.333,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 3,
  'DREB': 2,
  'REB': 5,
  'AST': 0,
  'STL': 1,
  'BLK': 0,
  'TOV': 0,
  'PF': 4,
  'PTS': 16,
  'PLUS_MINUS': 2,
  'FANTASY_PTS': 25.0,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1630578,
  'PLAYER_NAME': 'Alperen Sengun',
  'TEAM_ID': 1610612745,
  'TEAM_ABBREVIATION': 'HOU',
  'TEAM_NAME': 'Houston Rockets',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'HOU @ OKC',
  'WL': 'L',
  'MIN': 49,
  'FGM': 12,
  'FGA': 24,
  'FG_PCT': 0.5,
  'FG3M': 5,
  'FG3A': 8,
  'FG3_PCT': 0.625,
  'FTM': 10,
  'FTA': 11,
  'FT_PCT': 0.909,
  'OREB': 4,
  'DREB': 7,
  'REB': 11,
  'AST': 7,
  'STL': 2,
  'BLK': 1,
  'TOV': 4,
  'PF': 5,
  'PTS': 39,
  'PLUS_MINUS': 9,
  'FANTASY_PTS': 67.7,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1629006,
  'PLAYER_NAME': 'Josh Okogie',
  'TEAM_ID': 1610612745,
  'TEAM_ABBREVIATION': 'HOU',
  'TEAM_NAME': 'Houston Rockets',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'HOU @ OKC',
  'WL': 'L',
  'MIN': 20,
  'FGM': 1,
  'FGA': 3,
  'FG_PCT': 0.333,
  'FG3M': 1,
  'FG3A': 3,
  'FG3_PCT': 0.333,
  'FTM': 5,
  'FTA': 6,
  'FT_PCT': 0.833,
  'OREB': 1,
  'DREB': 1,
  'REB': 2,
  'AST': 1,
  'STL': 0,
  'BLK': 1,
  'TOV': 0,
  'PF': 2,
  'PTS': 8,
  'PLUS_MINUS': -8,
  'FANTASY_PTS': 14.9,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 203991,
  'PLAYER_NAME': 'Clint Capela',
  'TEAM_ID': 1610612745,
  'TEAM_ABBREVIATION': 'HOU',
  'TEAM_NAME': 'Houston Rockets',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'HOU @ OKC',
  'WL': 'L',
  'MIN': 8,
  'FGM': 1,
  'FGA': 1,
  'FG_PCT': 1.0,
  'FG3M': 0,
  'FG3A': 0,
  'FG3_PCT': None,
  'FTM': 2,
  'FTA': 2,
  'FT_PCT': 1.0,
  'OREB': 0,
  'DREB': 0,
  'REB': 0,
  'AST': 0,
  'STL': 1,
  'BLK': 0,
  'TOV': 1,
  'PF': 0,
  'PTS': 4,
  'PLUS_MINUS': 5,
  'FANTASY_PTS': 6.0,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 203500,
  'PLAYER_NAME': 'Steven Adams',
  'TEAM_ID': 1610612745,
  'TEAM_ABBREVIATION': 'HOU',
  'TEAM_NAME': 'Houston Rockets',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'HOU @ OKC',
  'WL': 'L',
  'MIN': 37,
  'FGM': 1,
  'FGA': 4,
  'FG_PCT': 0.25,
  'FG3M': 0,
  'FG3A': 0,
  'FG3_PCT': None,
  'FTM': 2,
  'FTA': 2,
  'FT_PCT': 1.0,
  'OREB': 5,
  'DREB': 8,
  'REB': 13,
  'AST': 3,
  'STL': 0,
  'BLK': 0,
  'TOV': 3,
  'PF': 4,
  'PTS': 4,
  'PLUS_MINUS': 2,
  'FANTASY_PTS': 21.1,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 201142,
  'PLAYER_NAME': 'Kevin Durant',
  'TEAM_ID': 1610612745,
  'TEAM_ABBREVIATION': 'HOU',
  'TEAM_NAME': 'Houston Rockets',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'HOU @ OKC',
  'WL': 'L',
  'MIN': 47,
  'FGM': 9,
  'FGA': 16,
  'FG_PCT': 0.563,
  'FG3M': 0,
  'FG3A': 4,
  'FG3_PCT': 0.0,
  'FTM': 5,
  'FTA': 6,
  'FT_PCT': 0.833,
  'OREB': 0,
  'DREB': 9,
  'REB': 9,
  'AST': 3,
  'STL': 0,
  'BLK': 0,
  'TOV': 4,
  'PF': 6,
  'PTS': 23,
  'PLUS_MINUS': 0,
  'FANTASY_PTS': 34.3,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1631222,
  'PLAYER_NAME': 'Jake LaRavia',
  'TEAM_ID': 1610612747,
  'TEAM_ABBREVIATION': 'LAL',
  'TEAM_NAME': 'Los Angeles Lakers',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'LAL vs. GSW',
  'WL': 'L',
  'MIN': 16,
  'FGM': 2,
  'FGA': 4,
  'FG_PCT': 0.5,
  'FG3M': 1,
  'FG3A': 2,
  'FG3_PCT': 0.5,
  'FTM': 0,
  'FTA': 2,
  'FT_PCT': 0.0,
  'OREB': 2,
  'DREB': 1,
  'REB': 3,
  'AST': 0,
  'STL': 0,
  'BLK': 0,
  'TOV': 0,
  'PF': 1,
  'PTS': 5,
  'PLUS_MINUS': -5,
  'FANTASY_PTS': 8.6,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1627741,
  'PLAYER_NAME': 'Buddy Hield',
  'TEAM_ID': 1610612744,
  'TEAM_ABBREVIATION': 'GSW',
  'TEAM_NAME': 'Golden State Warriors',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'GSW @ LAL',
  'WL': 'W',
  'MIN': 22,
  'FGM': 6,
  'FGA': 11,
  'FG_PCT': 0.545,
  'FG3M': 5,
  'FG3A': 10,
  'FG3_PCT': 0.5,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 0,
  'DREB': 1,
  'REB': 1,
  'AST': 0,
  'STL': 1,
  'BLK': 0,
  'TOV': 2,
  'PF': 0,
  'PTS': 17,
  'PLUS_MINUS': 5,
  'FANTASY_PTS': 19.2,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1629637,
  'PLAYER_NAME': 'Jaxson Hayes',
  'TEAM_ID': 1610612747,
  'TEAM_ABBREVIATION': 'LAL',
  'TEAM_NAME': 'Los Angeles Lakers',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'LAL vs. GSW',
  'WL': 'L',
  'MIN': 14,
  'FGM': 2,
  'FGA': 3,
  'FG_PCT': 0.667,
  'FG3M': 0,
  'FG3A': 0,
  'FG3_PCT': None,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 2,
  'DREB': 4,
  'REB': 6,
  'AST': 1,
  'STL': 0,
  'BLK': 0,
  'TOV': 1,
  'PF': 2,
  'PTS': 4,
  'PLUS_MINUS': -6,
  'FANTASY_PTS': 11.7,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 202710,
  'PLAYER_NAME': 'Jimmy Butler III',
  'TEAM_ID': 1610612744,
  'TEAM_ABBREVIATION': 'GSW',
  'TEAM_NAME': 'Golden State Warriors',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'GSW @ LAL',
  'WL': 'W',
  'MIN': 35,
  'FGM': 7,
  'FGA': 14,
  'FG_PCT': 0.5,
  'FG3M': 1,
  'FG3A': 2,
  'FG3_PCT': 0.5,
  'FTM': 16,
  'FTA': 16,
  'FT_PCT': 1.0,
  'OREB': 2,
  'DREB': 3,
  'REB': 5,
  'AST': 4,
  'STL': 1,
  'BLK': 0,
  'TOV': 1,
  'PF': 4,
  'PTS': 31,
  'PLUS_MINUS': 20,
  'FANTASY_PTS': 45.0,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 203110,
  'PLAYER_NAME': 'Draymond Green',
  'TEAM_ID': 1610612744,
  'TEAM_ABBREVIATION': 'GSW',
  'TEAM_NAME': 'Golden State Warriors',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'GSW @ LAL',
  'WL': 'W',
  'MIN': 28,
  'FGM': 3,
  'FGA': 6,
  'FG_PCT': 0.5,
  'FG3M': 1,
  'FG3A': 3,
  'FG3_PCT': 0.333,
  'FTM': 1,
  'FTA': 3,
  'FT_PCT': 0.333,
  'OREB': 1,
  'DREB': 6,
  'REB': 7,
  'AST': 9,
  'STL': 1,
  'BLK': 2,
  'TOV': 4,
  'PF': 5,
  'PTS': 8,
  'PLUS_MINUS': 20,
  'FANTASY_PTS': 34.9,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1629216,
  'PLAYER_NAME': 'Gabe Vincent',
  'TEAM_ID': 1610612747,
  'TEAM_ABBREVIATION': 'LAL',
  'TEAM_NAME': 'Los Angeles Lakers',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'LAL vs. GSW',
  'WL': 'L',
  'MIN': 29,
  'FGM': 1,
  'FGA': 4,
  'FG_PCT': 0.25,
  'FG3M': 1,
  'FG3A': 4,
  'FG3_PCT': 0.25,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 0,
  'DREB': 0,
  'REB': 0,
  'AST': 1,
  'STL': 1,
  'BLK': 0,
  'TOV': 0,
  'PF': 3,
  'PTS': 3,
  'PLUS_MINUS': -5,
  'FANTASY_PTS': 7.5,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1630228,
  'PLAYER_NAME': 'Jonathan Kuminga',
  'TEAM_ID': 1610612744,
  'TEAM_ABBREVIATION': 'GSW',
  'TEAM_NAME': 'Golden State Warriors',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'GSW @ LAL',
  'WL': 'W',
  'MIN': 33,
  'FGM': 6,
  'FGA': 11,
  'FG_PCT': 0.545,
  'FG3M': 4,
  'FG3A': 6,
  'FG3_PCT': 0.667,
  'FTM': 1,
  'FTA': 2,
  'FT_PCT': 0.5,
  'OREB': 3,
  'DREB': 6,
  'REB': 9,
  'AST': 6,
  'STL': 1,
  'BLK': 0,
  'TOV': 2,
  'PF': 3,
  'PTS': 17,
  'PLUS_MINUS': 4,
  'FANTASY_PTS': 37.8,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1629029,
  'PLAYER_NAME': 'Luka Dončić',
  'TEAM_ID': 1610612747,
  'TEAM_ABBREVIATION': 'LAL',
  'TEAM_NAME': 'Los Angeles Lakers',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'LAL vs. GSW',
  'WL': 'L',
  'MIN': 41,
  'FGM': 17,
  'FGA': 27,
  'FG_PCT': 0.63,
  'FG3M': 2,
  'FG3A': 10,
  'FG3_PCT': 0.2,
  'FTM': 7,
  'FTA': 10,
  'FT_PCT': 0.7,
  'OREB': 0,
  'DREB': 12,
  'REB': 12,
  'AST': 9,
  'STL': 2,
  'BLK': 1,
  'TOV': 3,
  'PF': 1,
  'PTS': 43,
  'PLUS_MINUS': -8,
  'FANTASY_PTS': 76.9,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 201143,
  'PLAYER_NAME': 'Al Horford',
  'TEAM_ID': 1610612744,
  'TEAM_ABBREVIATION': 'GSW',
  'TEAM_NAME': 'Golden State Warriors',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'GSW @ LAL',
  'WL': 'W',
  'MIN': 20,
  'FGM': 2,
  'FGA': 7,
  'FG_PCT': 0.286,
  'FG3M': 1,
  'FG3A': 4,
  'FG3_PCT': 0.25,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 0,
  'DREB': 5,
  'REB': 5,
  'AST': 1,
  'STL': 0,
  'BLK': 0,
  'TOV': 2,
  'PF': 4,
  'PTS': 5,
  'PLUS_MINUS': -10,
  'FANTASY_PTS': 10.5,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1642349,
  'PLAYER_NAME': 'Ajay Mitchell',
  'TEAM_ID': 1610612760,
  'TEAM_ABBREVIATION': 'OKC',
  'TEAM_NAME': 'Oklahoma City Thunder',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'OKC vs. HOU',
  'WL': 'W',
  'MIN': 15,
  'FGM': 6,
  'FGA': 12,
  'FG_PCT': 0.5,
  'FG3M': 3,
  'FG3A': 6,
  'FG3_PCT': 0.5,
  'FTM': 1,
  'FTA': 1,
  'FT_PCT': 1.0,
  'OREB': 1,
  'DREB': 1,
  'REB': 2,
  'AST': 2,
  'STL': 0,
  'BLK': 1,
  'TOV': 0,
  'PF': 2,
  'PTS': 16,
  'PLUS_MINUS': 2,
  'FANTASY_PTS': 24.4,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1629060,
  'PLAYER_NAME': 'Rui Hachimura',
  'TEAM_ID': 1610612747,
  'TEAM_ABBREVIATION': 'LAL',
  'TEAM_NAME': 'Los Angeles Lakers',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'LAL vs. GSW',
  'WL': 'L',
  'MIN': 35,
  'FGM': 3,
  'FGA': 6,
  'FG_PCT': 0.5,
  'FG3M': 3,
  'FG3A': 6,
  'FG3_PCT': 0.5,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 0,
  'DREB': 4,
  'REB': 4,
  'AST': 3,
  'STL': 0,
  'BLK': 0,
  'TOV': 1,
  'PF': 2,
  'PTS': 9,
  'PLUS_MINUS': -6,
  'FANTASY_PTS': 17.3,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1630611,
  'PLAYER_NAME': 'Gui Santos',
  'TEAM_ID': 1610612744,
  'TEAM_ABBREVIATION': 'GSW',
  'TEAM_NAME': 'Golden State Warriors',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'GSW @ LAL',
  'WL': 'W',
  'MIN': 3,
  'FGM': 0,
  'FGA': 0,
  'FG_PCT': None,
  'FG3M': 0,
  'FG3A': 0,
  'FG3_PCT': None,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 0,
  'DREB': 0,
  'REB': 0,
  'AST': 0,
  'STL': 0,
  'BLK': 0,
  'TOV': 1,
  'PF': 0,
  'PTS': 0,
  'PLUS_MINUS': 0,
  'FANTASY_PTS': -1.0,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1642954,
  'PLAYER_NAME': 'Will Richard',
  'TEAM_ID': 1610612744,
  'TEAM_ABBREVIATION': 'GSW',
  'TEAM_NAME': 'Golden State Warriors',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'GSW @ LAL',
  'WL': 'W',
  'MIN': 14,
  'FGM': 2,
  'FGA': 2,
  'FG_PCT': 1.0,
  'FG3M': 1,
  'FG3A': 1,
  'FG3_PCT': 1.0,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 1,
  'DREB': 0,
  'REB': 1,
  'AST': 1,
  'STL': 1,
  'BLK': 0,
  'TOV': 0,
  'PF': 2,
  'PTS': 5,
  'PLUS_MINUS': -11,
  'FANTASY_PTS': 10.7,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1627780,
  'PLAYER_NAME': 'Gary Payton II',
  'TEAM_ID': 1610612744,
  'TEAM_ABBREVIATION': 'GSW',
  'TEAM_NAME': 'Golden State Warriors',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'GSW @ LAL',
  'WL': 'W',
  'MIN': 12,
  'FGM': 3,
  'FGA': 6,
  'FG_PCT': 0.5,
  'FG3M': 0,
  'FG3A': 1,
  'FG3_PCT': 0.0,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 1,
  'DREB': 1,
  'REB': 2,
  'AST': 1,
  'STL': 1,
  'BLK': 1,
  'TOV': 3,
  'PF': 3,
  'PTS': 6,
  'PLUS_MINUS': 3,
  'FANTASY_PTS': 12.9,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1631106,
  'PLAYER_NAME': 'Tari Eason',
  'TEAM_ID': 1610612745,
  'TEAM_ABBREVIATION': 'HOU',
  'TEAM_NAME': 'Houston Rockets',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'HOU @ OKC',
  'WL': 'L',
  'MIN': 22,
  'FGM': 1,
  'FGA': 6,
  'FG_PCT': 0.167,
  'FG3M': 1,
  'FG3A': 4,
  'FG3_PCT': 0.25,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 0,
  'DREB': 6,
  'REB': 6,
  'AST': 0,
  'STL': 0,
  'BLK': 1,
  'TOV': 4,
  'PF': 1,
  'PTS': 3,
  'PLUS_MINUS': -4,
  'FANTASY_PTS': 9.2,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1641764,
  'PLAYER_NAME': 'Brandin Podziemski',
  'TEAM_ID': 1610612744,
  'TEAM_ABBREVIATION': 'GSW',
  'TEAM_NAME': 'Golden State Warriors',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'GSW @ LAL',
  'WL': 'W',
  'MIN': 33,
  'FGM': 3,
  'FGA': 7,
  'FG_PCT': 0.429,
  'FG3M': 1,
  'FG3A': 4,
  'FG3_PCT': 0.25,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 1,
  'DREB': 6,
  'REB': 7,
  'AST': 2,
  'STL': 1,
  'BLK': 0,
  'TOV': 1,
  'PF': 2,
  'PTS': 7,
  'PLUS_MINUS': 13,
  'FANTASY_PTS': 20.4,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1629028,
  'PLAYER_NAME': 'Deandre Ayton',
  'TEAM_ID': 1610612747,
  'TEAM_ABBREVIATION': 'LAL',
  'TEAM_NAME': 'Los Angeles Lakers',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'LAL vs. GSW',
  'WL': 'L',
  'MIN': 34,
  'FGM': 5,
  'FGA': 7,
  'FG_PCT': 0.714,
  'FG3M': 0,
  'FG3A': 0,
  'FG3_PCT': None,
  'FTM': 0,
  'FTA': 2,
  'FT_PCT': 0.0,
  'OREB': 2,
  'DREB': 4,
  'REB': 6,
  'AST': 0,
  'STL': 0,
  'BLK': 1,
  'TOV': 4,
  'PF': 3,

In [4]:
extract_df.keys()

Index(['SEASON_ID', 'PLAYER_ID', 'PLAYER_NAME', 'TEAM_ID', 'TEAM_ABBREVIATION',
       'TEAM_NAME', 'GAME_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'FGM',
       'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT',
       'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'PLUS_MINUS', 'FANTASY_PTS', 'VIDEO_AVAILABLE'],
      dtype='str')

In [5]:
from nba_api.stats.static import players

In [6]:
player_search = players.find_players_by_full_name('Luka Doncic')

In [7]:
player_search

[{'id': 1629029,
  'full_name': 'Luka Dončić',
  'first_name': 'Luka',
  'last_name': 'Dončić',
  'is_active': True}]

In [17]:
from nba_api.stats.endpoints import scheduleleaguev2

In [18]:
schedule = scheduleleaguev2.ScheduleLeagueV2()

In [10]:
schedule.get_data_frames()[0]

,leagueId,seasonYear,gameDate,gameId,gameCode,gameStatus,gameStatusText,gameSequence,gameDateEst,gameTimeEst,...,awayOttBroadcasters_broadcasterMedia,awayOttBroadcasters_broadcasterId,awayOttBroadcasters_broadcasterDisplay,awayOttBroadcasters_broadcasterAbbreviation,awayOttBroadcasters_broadcasterDescription,awayOttBroadcasters_tapeDelayComments,awayOttBroadcasters_broadcasterVideoLink,awayOttBroadcasters_broadcasterTeamId,awayOttBroadcasters_broadcasterRanking,awayOttBroadcasters_localizationRegion
0,00,2025-26,10/02/2025 00:00:00,0012500008,20251002/PHINYK,3,Final,1,2025-10-02T00:00:00Z,1900-01-01T12:00:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
1,00,2025-26,10/03/2025 00:00:00,0012500001,20251003/PHXLAL,3,Final,2,2025-10-03T00:00:00Z,1900-01-01T22:00:00Z,...,ott,1001033.0,Suns+,DTC-PHX,,,,1.610613e+09,None,
2,00,2025-26,10/03/2025 00:00:00,0012500009,20251003/MELNOP,3,Final,1,2025-10-03T00:00:00Z,1900-01-01T05:30:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
3,00,2025-26,10/04/2025 00:00:00,0012500010,20251004/NYKPHI,3,Final,1,2025-10-04T00:00:00Z,1900-01-01T11:00:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
4,00,2025-26,10/04/2025 00:00:00,0012500011,20251004/SEMNOP,3,Final,5,2025-10-04T00:00:00Z,1900-01-01T23:00:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1317,00,2025-26,06/08/2026 00:00:00,0042500403,,1,8:30 pm ET,1,2026-06-08T00:00:00Z,1900-01-01T20:30:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
1318,00,2025-26,06/10/2026 00:00:00,0042500404,,1,8:30 pm ET,1,2026-06-10T00:00:00Z,1900-01-01T20:30:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
1319,00,2025-26,06/13/2026 00:00:00,0042500405,,1,8:30 pm ET,1,2026-06-13T00:00:00Z,1900-01-01T20:30:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
1320,00,2025-26,06/16/2026 00:00:00,0042500406,,1,8:30 pm ET,1,2026-06-16T00:00:00Z,1900-01-01T20:30:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
1321,00,2025-26,06/19/2026 00:00:00,0042500407,,1,8:30 pm ET,1,2026-06-19T00:00:00Z,1900-01-01T20:30:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN

In [11]:
schedule.get_data_frames()[1]

,leagueId,seasonYear,weekNumber,weekName,startDate,endDate
0,00,2025-26,1,Week 1,2025-10-21T00:00:00Z,2025-10-26T00:00:00Z
1,00,2025-26,2,Week 2,2025-10-27T00:00:00Z,2025-11-02T00:00:00Z
2,00,2025-26,3,Week 3,2025-11-03T00:00:00Z,2025-11-09T00:00:00Z
3,00,2025-26,4,Week 4,2025-11-10T00:00:00Z,2025-11-16T00:00:00Z
4,00,2025-26,5,Week 5,2025-11-17T00:00:00Z,2025-11-23T00:00:00Z
5,00,2025-26,6,Week 6,2025-11-24T00:00:00Z,2025-11-30T00:00:00Z
6,00,2025-26,7,Week 7,2025-12-01T00:00:00Z,2025-12-07T00:00:00Z
7,00,2025-26,8,Week 8,2025-12-08T00:00:00Z,2025-12-14T00:00:00Z
8,00,2025-26,9,Week 9,2025-12-15T00:00:00Z,2025-12-21T00:00:00Z
9,00,2025-26,10,Week 10,2025-12-22T00:00:00Z,2025-12-28T00:00:00Z
10,00,2025-26,11,Week 11,2025-12-29T00:00:00Z,2026-01-04T00:00:00Z
11,00,2025-26,12,Week 12,2026-01-05T00:00:00Z,2026-01-11T00:00:00Z
12,00,2025-26,13,Week 13,2026-01-12T00:00:00Z,2026-01-18T00:00:00Z
13,00,2025-26,14,Week 14,2026-01-19T00:00:00Z,2026-01-25T00:00:00Z
14,00,2025-26,15,Week 15,2026-01-26T00:00:00Z,2026-02-01T00:00:00Z
15,00,2025-26,16,Week 16,2026-02-02T00:00:00Z,2026-02-08T00:00:00Z
16,00,2025-26,17,Week 17,2026-02-09T00:00:00Z,2026-02-15T00:00:00Z
17,00,2025-26,18,Week 18,2026-02-16T00:00:00Z,2026-02-22T00:00:00Z
18,00,2025-26,19,Week 19,2026-02-23T00:00:00Z,2026-03-01T00:00:00Z
19,00,2025-26,20,Week 20,2026-03-02T00:00:00Z,2026-03-08T00:00:00Z
20,00,2025-26,21,Week 21,2026-03-09T00:00:00Z,2026-03-15T00:00:00Z
21,00,2025-26,22,Week 22,2026-03-16T00:00:00Z,2026-03-22T00:00:00Z
22,00,2025-26,23,Week 23,2026-03-23T00:00:00Z,2026-03-29T00:00:00Z
23,00,2025-26,24,Week 24,2026-03-30T00:00:00Z,2026-04-05T00:00:00Z
24,00,2025-26,25,Week 25,2026-04-06T00:00:00Z,2026-04-12T00:00:00Z
25,00,2025-26,26,Week 26,2026-04-13T00:00:00Z,2026-04-19T00:00:00Z
26,00,2025-26,27,Week 27,2026-04-20T00:00:00Z,2026-04-26T00:00:00Z
27,00,2025-26,28,Week 28,2026-04-27T00:00:00Z,2026-05-03T00:00:00Z
28,00,2025-26,29,Week 29,2026-05-04T00:00:00Z,2026-05-10T00:00:00Z
29,00,2025-26,30,Week 30,2026-05-11T00:00:00Z,2026-05-17T00:00:00Z
30,00,2025-26,31,Week 31,2026-05-18T00:00:00Z,2026-05-24T00:00:00Z
31,00,2025-26,32,Week 32,2026-05-25T00:00:00Z,2026-05-31T00:00:00Z
32,00,2025-26,33,Week 33,2026-06-01T00:00:00Z,2026-06-07T00:00:00Z
33,00,2025-26,34,Week 34,2026-06-08T00:00:00Z,2026-06-14T00:00:00Z
34,00,2025-26,35,Week 35,2026-06-15T00:00:00Z,2026-06-21T00:00:00Z
35,00,2025-26,26,Week 26,2026-04-13T00:00:00Z,2026-04-19T00:00:00Z
36,00,2025-26,9,Week 9,2025-12-15T00:00:00Z,2025-12-21T00:00:00Z
37,00,2025-26,17,All-Star,2026-02-09T00:00:00Z,2026-02-15T00:00:00Z

In [23]:
schedule_json = json.loads(schedule.get_json())

In [24]:
schedule_json.keys()

dict_keys(['meta', 'leagueSchedule'])

In [16]:
schedule_json['leagueSchedule'].keys()

dict_keys(['seasonYear', 'leagueId', 'gameDates', 'weeks'])

In [37]:
schedule_json['leagueSchedule']['gameDates'][0]

{'gameDate': '10/02/2025 00:00:00',
 'games': [{'gameId': '0012500008',
   'gameCode': '20251002/PHINYK',
   'gameStatus': 3,
   'gameStatusText': 'Final',
   'gameSequence': 1,
   'gameDateEst': '2025-10-02T00:00:00Z',
   'gameTimeEst': '1900-01-01T12:00:00Z',
   'gameDateTimeEst': '2025-10-02T12:00:00Z',
   'gameDateUTC': '2025-10-02T04:00:00Z',
   'gameTimeUTC': '1900-01-01T16:00:00Z',
   'gameDateTimeUTC': '2025-10-02T16:00:00Z',
   'awayTeamTime': '2025-10-02T12:00:00Z',
   'homeTeamTime': '2025-10-02T12:00:00Z',
   'day': 'Thu',
   'monthNum': 10,
   'weekNumber': 0,
   'weekName': '',
   'ifNecessary': 'false',
   'seriesGameNumber': '',
   'gameLabel': 'Preseason',
   'gameSubLabel': 'NBA Abu Dhabi Game',
   'seriesText': 'Neutral Site',
   'arenaName': 'Etihad Arena',
   'arenaState': '',
   'arenaCity': 'Abu Dhabi',
   'postponedStatus': 'N',
   'branchLink': '',
   'gameSubtype': 'Global Games',
   'isNeutral': True,
   'broadcasters': {'nationalBroadcasters': [{'broadcasterScope': 'natl',
      'broadcasterMedia': 'tv',
      'broadcasterId': 7,
      'broadcasterDisplay': 'NBA TV',
      'broadcasterAbbreviation': 'NBA TV',
      'broadcasterDescription': 'Watch with League Pass or your TV subscription',
      'tapeDelayComments': '',
      'broadcasterVideoLink': '',
      'broadcasterTeamId': -1,
      'broadcasterRanking': None,
      'localizationRegion': ''}],
    'nationalRadioBroadcasters': [],
    'nationalOttBroadcasters': [],
    'homeTvBroadcasters': [{'broadcasterScope': 'home',
      'broadcasterMedia': 'tv',
      'broadcasterId': 100,
      'broadcasterDisplay': 'Gotham',
      'broadcasterAbbreviation': 'MSG',
      'broadcasterDescription': '',
      'tapeDelayComments': '',
      'broadcasterVideoLink': '',
      'broadcasterTeamId': 1610612752,
      'broadcasterRanking': None,
      'localizationRegion': ''}],
    'homeRadioBroadcasters': [],
    'homeOttBroadcasters': [],
    'awayTvBroadcasters': [],
    'awayRadioBroadcasters': [],
    'awayOttBroadcasters': []},
   'homeTeam': {'teamId': 1610612752,
    'teamName': 'Knicks',
    'teamCity': 'New York',
    'teamTricode': 'NYK',
    'teamSlug': 'knicks',
    'wins': 1,
    'losses': 0,
    'score': 99,
    'seed': 0},
   'awayTeam': {'teamId': 1610612755,
    'teamName': '76ers',
    'teamCity': 'Philadelphia',
    'teamTricode': 'PHI',
    'teamSlug': 'sixers',
    'wins': 0,
    'losses': 1,
    'score': 84,
    'seed': 0},
   'pointsLeaders': [{'personId': 1630178,
     'firstName': 'Tyrese',
     'lastName': 'Maxey',
     'teamId': 1610612755,
     'teamCity': 'Philadelphia',
     'teamName': '76ers',
     'teamTricode': 'PHI',
     'points': 14.0},
    {'personId': 1642845,
     'firstName': 'Valdez',
     'lastName': 'Edgecombe',
     'teamId': 1610612755,
     'teamCity': 'Philadelphia',
     'teamName': '76ers',
     'teamTricode': 'PHI',
     'points': 14.0}]}]}

In [39]:
schedule_json['leagueSchedule']['gameDates'][0]['games'][0].keys()

dict_keys(['gameId', 'gameCode', 'gameStatus', 'gameStatusText', 'gameSequence', 'gameDateEst', 'gameTimeEst', 'gameDateTimeEst', 'gameDateUTC', 'gameTimeUTC', 'gameDateTimeUTC', 'awayTeamTime', 'homeTeamTime', 'day', 'monthNum', 'weekNumber', 'weekName', 'ifNecessary', 'seriesGameNumber', 'gameLabel', 'gameSubLabel', 'seriesText', 'arenaName', 'arenaState', 'arenaCity', 'postponedStatus', 'branchLink', 'gameSubtype', 'isNeutral', 'broadcasters', 'homeTeam', 'awayTeam', 'pointsLeaders'])